export const PREFECT_POSITIONS = {
  HEAD_PREFECT: 'HEAD_PREFECT',
  DEPUTY_HEAD_PREFECT: 'DEPUTY_HEAD_PREFECT',
  SPORTS_PREFECT: 'SPORTS_PREFECT',
  LIBRARY_PREFECT: 'LIBRARY_PREFECT',
  DISCIPLINE_PREFECT: 'DISCIPLINE_PREFECT',
  CULTURAL_PREFECT: 'CULTURAL_PREFECT',
  ACADEMIC_PREFECT: 'ACADEMIC_PREFECT',
  SOCIAL_SERVICE_PREFECT: 'SOCIAL_SERVICE_PREFECT',
};
